/*
 * Embedded word list for training. Filtered at runtime by introduced letters.
 * Contains 1500 common English words (2-8 letters, a-z only).
 */
#pragma once

static const char * const WORDLIST[] = {
    // 2-letter words (25)
    "am", "an", "as", "at", "be", "by", "do", "go", "he", "if", "in", "is",
    "it", "me", "my", "no", "of", "ok", "on", "or", "so", "to", "up", "us",
    "we",
    // 3-letter words (130)
    "ace", "add", "age", "ago", "aid", "aim", "air", "all", "and", "any", "ape", "arc",
    "are", "ark", "arm", "art", "ash", "ask", "ate", "axe", "bad", "bag", "ban", "bar",
    "bat", "bay", "bed", "bet", "big", "bin", "bit", "bow", "box", "boy", "bud", "bug",
    "bun", "bus", "but", "buy", "cab", "can", "cap", "car", "cat", "cop", "cow", "cry",
    "cub", "cup", "cut", "dab", "dad", "dam", "day", "den", "dew", "did", "dig", "dim",
    "dip", "dog", "dot", "dry", "dub", "dud", "due", "dug", "duo", "dye", "ear", "eat",
    "egg", "elm", "end", "era", "eve", "ewe", "eye", "fan", "far", "fat", "fed", "few",
    "fig", "fin", "fit", "fix", "fly", "foe", "fog", "for", "fox", "fry", "fun", "fur",
    "gag", "gap", "gas", "get", "god", "got", "gum", "gun", "gut", "guy", "gym", "had",
    "ham", "has", "hat", "hay", "hen", "her", "hid", "him", "hip", "his", "hit", "hog",
    "hop", "hot", "how", "hub", "hue", "hug", "hum", "hut", "ice", "icy",
    // 4-letter words (300)
    "able", "ache", "acid", "acre", "aged", "aide", "ally", "also", "arch", "area",
    "army", "atom", "auto", "avid", "away", "axle", "baby", "back", "bail", "bait",
    "bake", "bald", "bale", "ball", "band", "bane", "bang", "bank", "bare", "bark",
    "barn", "base", "bath", "bead", "beak", "beam", "bean", "bear", "beat", "been",
    "beer", "bell", "belt", "bend", "bent", "best", "bike", "bill", "bind", "bird",
    "bite", "blew", "blob", "blot", "blow", "blue", "blur", "boar", "boat", "body",
    "bold", "bolt", "bomb", "bond", "bone", "book", "boom", "boot", "bore", "born",
    "boss", "both", "bout", "bowl", "bran", "bred", "brew", "brim", "bulk", "bull",
    "bump", "burn", "bury", "bush", "busy", "buzz", "cafe", "cage", "cake", "calf",
    "call", "calm", "came", "camp", "cane", "cape", "card", "care", "cart", "case",
    "cash", "cast", "cave", "chap", "chat", "chef", "chin", "chip", "chop", "cite",
    "city", "clad", "clam", "clap", "claw", "clay", "clip", "clod", "clog", "club",
    "clue", "coal", "coat", "code", "coil", "coin", "cold", "colt", "comb", "come",
    "cook", "cool", "cope", "copy", "cord", "core", "cork", "corn", "cost", "cosy",
    "coup", "crab", "crew", "crop", "crow", "cube", "cult", "curb", "cure", "curl",
    "cute", "damp", "dare", "dark", "dart", "dash", "data", "dawn", "dead", "deaf",
    "deal", "dean", "dear", "debt", "deck", "deed", "deem", "deep", "deer", "deny",
    "desk", "dial", "dice", "diet", "dirt", "dock", "does", "dome", "done", "doom",
    "door", "dose", "down", "doze", "drag", "draw", "drew", "drip", "drop", "drum",
    "dual", "duck", "duel", "dull", "dumb", "dump", "dune", "dusk", "dust", "duty",
    "each", "earl", "earn", "ease", "east", "easy", "edge", "else", "emit", "envy",
    "epic", "even", "ever", "evil", "exam", "exit", "face", "fact", "fade", "fail",
    "fair", "fake", "fall", "fame", "fare", "farm", "fast", "fate", "fawn", "fear",
    "feat", "feed", "feel", "feet", "fell", "felt", "fend", "file", "fill", "film",
    "find", "fine", "fire", "firm", "fist", "five", "flag", "flap", "flat", "flaw",
    "flea", "fled", "flee", "flew", "flip", "flog", "flow", "foam", "foil", "fold",
    "folk", "fond", "food", "fool", "foot", "ford", "fore", "fork", "form", "fort",
    "foul", "four", "free", "frog", "from", "fuel", "full", "fume", "fund", "fury",
    "fuse", "fuss", "gait", "gale", "game", "gang", "gape", "gash", "gasp", "gate",
    "gave", "gaze", "gear", "gift", "girl", "give", "glad", "goal", "goes", "gold",
    // 5-letter words (330)
    "abort", "about", "above", "abuse", "acorn", "acted", "admit", "adopt", "adult", "after",
    "again", "agent", "agree", "ahead", "aisle", "alarm", "album", "alert", "alien", "align",
    "alive", "alley", "allot", "allow", "aloft", "alone", "along", "aloof", "alter", "among",
    "ample", "angel", "anger", "angle", "angry", "ankle", "apart", "apple", "apply", "arena",
    "argue", "arise", "armor", "aroma", "arose", "aside", "asset", "atlas", "attic", "audio",
    "audit", "avail", "avoid", "awake", "award", "aware", "awful", "bacon", "badge", "badly",
    "baker", "baron", "basic", "basin", "basis", "batch", "beach", "begun", "being", "below",
    "bench", "berry", "birth", "black", "blade", "blame", "bland", "blank", "blast", "blaze",
    "bleed", "blend", "bless", "blind", "blink", "bliss", "block", "blond", "blood", "bloom",
    "blown", "board", "boast", "bonus", "booth", "bound", "boxer", "brace", "brain", "brand",
    "brass", "brave", "bread", "break", "breed", "brick", "bride", "brief", "bring", "broad",
    "broke", "brook", "broth", "brown", "brush", "budge", "build", "built", "bunch", "burst",
    "buyer", "cabin", "cable", "candy", "cargo", "carry", "catch", "cause", "cease", "chain",
    "chair", "chalk", "chant", "chaos", "charm", "chart", "chase", "cheap", "cheat", "check",
    "cheek", "cheer", "chess", "chest", "chief", "child", "chill", "chime", "choir", "chord",
    "chunk", "churn", "cider", "cigar", "civil", "claim", "clamp", "clash", "clasp", "class",
    "clean", "clear", "clerk", "climb", "cling", "cloak", "clock", "clone", "close", "cloth",
    "cloud", "clown", "coach", "coast", "color", "comet", "coral", "couch", "could", "count",
    "court", "cover", "crack", "craft", "crane", "crash", "crate", "crawl", "crazy", "cream",
    "creep", "crest", "crime", "crisp", "cross", "crowd", "crown", "crude", "crush", "curve",
    "cycle", "daily", "dairy", "dance", "decay", "decor", "decoy", "delay", "demon", "dense",
    "depot", "depth", "derby", "devil", "diary", "dirty", "dodge", "doubt", "dough", "draft",
    "drain", "drama", "drank", "drape", "drawn", "dread", "dream", "dress", "dried", "drift",
    "drill", "drink", "drive", "drown", "drunk", "dryer", "dusty", "dwarf", "dwell", "dying",
    "eager", "early", "earth", "eight", "elbow", "elder", "elect", "elite", "ember", "empty",
    "enemy", "enjoy", "enter", "equal", "equip", "erase", "error", "essay", "event", "every",
    "exact", "exile", "exist", "extra", "fable", "faint", "fairy", "faith", "false", "fault",
    "favor", "feast", "fence", "ferry", "fewer", "fiber", "field", "fifth", "fifty", "fight",
    "final", "first", "fixed", "flame", "flash", "flask", "flesh", "flick", "float", "flock",
    "flood", "floor", "flour", "flown", "fluid", "flush", "flute", "focal", "focus", "force",
    "forge", "forth", "forum", "found", "frame", "frank", "fraud", "fresh", "front", "frost",
    "froze", "fruit", "fully", "funny", "giant", "given", "glare", "glass", "gleam", "glide",
    "globe", "gloom", "glory", "glove", "gnome", "goose", "grace", "grade", "grain", "grand",
    // 6-letter words (300)
    "absorb", "accent", "accept", "access", "accord", "accuse", "across", "acting",
    "action", "active", "actual", "adjust", "admire", "advice", "advise", "afford",
    "afraid", "agency", "agenda", "almost", "always", "amount", "amused", "anchor",
    "animal", "annual", "answer", "anyone", "anyway", "appeal", "appear", "arctic",
    "argued", "around", "arrive", "artist", "assess", "assign", "assist", "assume",
    "attach", "attack", "attend", "author", "autumn", "avenue", "backed", "ballet",
    "bamboo", "banner", "barely", "barren", "basket", "battle", "beacon", "beauty",
    "became", "become", "before", "behalf", "behave", "behind", "belief", "belong",
    "beside", "better", "beyond", "bitter", "blanch", "bleach", "blonde", "borrow",
    "bother", "bottle", "bottom", "bounce", "branch", "breach", "breath", "bridge",
    "bright", "broken", "broker", "bronze", "bruise", "bubble", "budget", "bundle",
    "burden", "bureau", "burner", "butter", "button", "bypass", "cactus", "camera",
    "cancel", "candid", "cannon", "canopy", "canvas", "canyon", "carbon", "career",
    "carpet", "castle", "casual", "caught", "causal", "cavity", "center", "chance",
    "change", "chapel", "charge", "cheese", "choice", "choose", "chosen", "church",
    "circle", "clause", "client", "climax", "clinic", "clumsy", "coarse", "cobalt",
    "coffee", "collar", "colony", "column", "combat", "comedy", "coming", "commit",
    "common", "convey", "cookie", "cooler", "copper", "corner", "cosmic", "cotton",
    "county", "couple", "course", "cousin", "cradle", "create", "credit", "crisis",
    "critic", "cruise", "cuddle", "custom", "damage", "dancer", "danger", "debate",
    "debris", "decade", "decent", "decide", "decree", "defeat", "defend", "degree",
    "demand", "denial", "depend", "depict", "deploy", "desert", "design", "desire",
    "detail", "detect", "devote", "differ", "digest", "dimple", "dinner", "direct",
    "divide", "domain", "donate", "double", "dragon", "drawer", "during", "earned",
    "easily", "eating", "editor", "effect", "effort", "eighth", "either", "eleven",
    "embark", "emerge", "empire", "employ", "enable", "ending", "endure", "energy",
    "engage", "engine", "enough", "ensure", "entire", "entity", "equity", "errand",
    "escape", "estate", "evolve", "exceed", "except", "excite", "excuse", "expand",
    "expect", "expert", "export", "expose", "extend", "extent", "fabric", "fading",
    "fairly", "fallen", "family", "famous", "farmer", "father", "faucet", "fellow",
    "figure", "filter", "finish", "flavor", "flight", "flower", "flying", "follow",
    "forbid", "forced", "forest", "forget", "formal", "former", "fossil", "fought",
    "fourth", "freeze", "frenzy", "friend", "fright", "fringe", "frozen", "frugal",
    "fulfil", "funded", "future", "gadget", "gained", "gallon", "garden", "garlic",
    "gather", "gently", "gifted", "ginger", "giving", "global", "glossy", "golden",
    "gossip", "govern", "gravel", "growth", "guilty", "guitar", "gutter", "handle",
    "happen", "harbor", "hardly", "health", "heaven", "height", "helmet", "herbal",
    "hermit", "heroic", "hidden", "higher",
    // 7-letter words (250)
    "abandon", "ability", "absence", "abstain", "abusive", "account",
    "achieve", "acquire", "address", "adjourn", "adopted", "advance",
    "adverse", "adviser", "ailment", "airport", "alcohol", "already",
    "amazing", "ancient", "angular", "anxiety", "anybody", "apparel",
    "applied", "arrange", "article", "artwork", "assault", "attempt",
    "attract", "auction", "audible", "average", "awkward", "backing",
    "baggage", "balance", "balloon", "banking", "bargain", "barrier",
    "battery", "bearing", "because", "bedroom", "believe", "beneath",
    "benefit", "besides", "between", "billion", "blanket", "boiling",
    "bonfire", "booklet", "borough", "bottled", "boulder", "bracket",
    "breadth", "breathe", "brigade", "bristle", "brittle", "broadly",
    "brother", "brought", "buckets", "buffalo", "builder", "cabinet",
    "calcium", "capable", "captain", "capture", "careful", "caution",
    "ceiling", "central", "certain", "chamber", "channel", "chapter",
    "charity", "cheaper", "chiefly", "chimney", "circuit", "citizen",
    "claimed", "classic", "cleaner", "clearly", "climate", "closing",
    "cluster", "coating", "collect", "combine", "comfort", "command",
    "comment", "company", "compare", "compete", "complex", "compose",
    "concept", "concern", "conduct", "confess", "confide", "confirm",
    "confuse", "connect", "consent", "consist", "contain", "content",
    "contest", "context", "control", "convert", "cooking", "correct",
    "cottage", "council", "counsel", "counter", "country", "courage",
    "covered", "creator", "cricket", "crimson", "crucial", "crystal",
    "cuisine", "culture", "current", "cushion", "customs", "cutting",
    "damaged", "dealing", "decline", "declare", "default", "defence",
    "deficit", "deliver", "density", "deposit", "descent", "despite",
    "destroy", "develop", "devoted", "dialect", "digital", "dignity",
    "dilemma", "diploma", "discuss", "disease", "dismiss", "display",
    "dispose", "dispute", "distant", "diverse", "divided", "dolphin",
    "donated", "doorway", "doubled", "drafted", "drawing", "durable",
    "dynamic", "earlier", "earnest", "earning", "eastern", "ecology",
    "economy", "edition", "educate", "elderly", "elegant", "element",
    "elevate", "embrace", "emotion", "emperor", "empower", "endless",
    "enforce", "engaged", "enhance", "enquiry", "episode", "erosion",
    "essence", "eternal", "ethical", "evening", "evident", "exactly",
    "examine", "example", "exclaim", "exclude", "exhaust", "exhibit",
    "expense", "explain", "explore", "exposed", "express", "extreme",
    "eyebrow", "faculty", "failure", "farming", "fashion", "fatigue",
    "feature", "fertile", "fiction", "fighter", "finance", "finding",
    "fitness", "flavour", "fleeing", "fluency", "foolish", "foreign",
    "forever", "formula", "fortune", "forward", "founder", "freedom",
    "freight", "fulfill", "funeral", "furnace",
    // 8-letter words (165)
    "absolute", "abstract", "academic", "accident", "accurate", "actively",
    "actually", "addition", "adjusted", "adequate", "advanced", "advocate",
    "affected", "afforded", "agreeing", "aircraft", "airtight", "alliance",
    "allowing", "alphabet", "although", "ambition", "amounted", "analysis",
    "ancestor", "animated", "announce", "annually", "anything", "anywhere",
    "apparent", "appetite", "applause", "approach", "approval", "argument",
    "arranged", "artistic", "assemble", "assuming", "athletic", "attorney",
    "audience", "backbone", "backward", "balanced", "bankrupt", "bathroom",
    "becoming", "behavior", "believed", "birthday", "blessing", "boundary",
    "breeding", "brighten", "bringing", "brothers", "browsing", "brushing",
    "building", "bulletin", "business", "calendar", "carefree", "campaign",
    "capacity", "cardinal", "carrying", "casualty", "cautious", "ceremony",
    "chairman", "champion", "changing", "charming", "cheating", "chemical",
    "children", "choosing", "citation", "civilian", "climbing", "clinical",
    "clothing", "coaching", "collapse", "colonial", "colorful", "combined",
    "comeback", "communal", "commuter", "compared", "compiler", "complete",
    "compound", "computer", "concrete", "conflict", "congress", "conserve",
    "consider", "consumer", "contempt", "continue", "contrast", "convince",
    "corridor", "covering", "creation", "creative", "creature", "criminal",
    "critique", "crossing", "cultural", "currency", "customer", "darkness",
    "database", "daughter", "deadline", "deciding", "decision", "declared",
    "decorate", "decrease", "dedicate", "defender", "definite", "delicate",
    "delegate", "delivery", "demanded", "democrat", "demolish", "departed",
    "describe", "designer", "detailed", "detector", "devotion", "dialogue",
    "dictator", "dinosaur", "diplomat", "directed", "director", "disabled",
    "disaster", "disclose", "discover", "disorder", "dispatch", "disposal",
    "dissolve", "distance", "distinct", "district", "division", "doctrine",
    "document", "domestic", "dominant",
};
#define WORDLIST_SIZE (sizeof(WORDLIST) / sizeof(WORDLIST[0]))

// Filter words eligible at current level (all chars in introduced set)
// Returns count of eligible words, fills `out` up to `out_max`
static int filter_words(const char *introduced, int intro_count,
                        const char **out, int out_max,
                        int min_len = 2, int max_len = 8) {
    int n = 0;
    for (int w = 0; w < (int)WORDLIST_SIZE && n < out_max; w++) {
        const char *word = WORDLIST[w];
        int len = strlen(word);
        if (len < min_len || len > max_len) continue;

        bool ok = true;
        for (int i = 0; i < len; i++) {
            char ch = word[i];
            bool found = false;
            for (int j = 0; j < intro_count; j++) {
                if (introduced[j] == ch) { found = true; break; }
            }
            if (!found) { ok = false; break; }
        }
        if (ok) out[n++] = word;
    }
    return n;
}
